version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventos_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_eventos:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/eventos_db

volumes:
  postgres_data_eventos:
