"""feat: Avance 2 P2

Revision ID: 295331c7fa6b
Revises: 
Create Date: 2026-07-31 18:41:53.445274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295331c7fa6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos'))
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_nombre'), ['nombre'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_nombre'), ['nombre'], unique=False)

    op.create_table('boletos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_boletos_evento_id_eventos')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_boletos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boletos'))
    )
    with op.batch_alter_table('boletos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boletos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boletos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boletos_id'))

    op.drop_table('boletos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_nombre'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_nombre'))
        batch_op.drop_index(batch_op.f('ix_eventos_id'))

    op.drop_table('eventos')
    # ### end Alembic commands ###
